version: '3.7'

# See https://github.com/prisma/prisma/blob/main/TESTING.md#environment-variables
services:
  postgres:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=tests
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
    ports:
      - '5432:5432'

  postgres_isolated:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=tests
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
    ports:
      - '5435:5432'

  cockroachdb:
    image: prismagraphql/build:cockroach-custom
    restart: always
    command: start-single-node --insecure
    ports:
      - '26257:26257'

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tests
      - MYSQL_USER=prisma
      - MYSQL_PASSWORD=prisma
    # https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    ports:
      - '3306:3306'
  mysql_isolated:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tests
      - MYSQL_USER=prisma
      - MYSQL_PASSWORD=prisma
    # https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    ports:
      - '3307:3306'
  mariadb:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tests
      - MYSQL_USER=prisma
      - MYSQL_PASSWORD=prisma
    ports:
      - '4306:3306'

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pr1sm4_Pr1sm4
    ports:
      - '1433:1433'

  # mongo:
  #   image: mongo:4
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: prisma
  #     MONGO_INITDB_DATABASE: tests
  #   ports:
  #     - '27017:27017'

  # mongo-seed:
  #   build: ./mongo-seed
  #   links:
  #     - mongo

  mongo5:
    image: prismagraphql/mongo-single-replica:5.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "prisma"
      MONGO_INITDB_ROOT_PASSWORD: "prisma"
      MONGO_PORT: 27018
      INIT_WAIT_SEC: $INIT_WAIT_SEC
    ports:
      - "27018:27018"
    # networks:
    #   - databases

  mongo5-single:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "prisma"
      MONGO_INITDB_ROOT_PASSWORD: "prisma"
      INIT_WAIT_SEC: $INIT_WAIT_SEC
    ports:
      - "27018:27017"
    # networks:
    #   - databases

networks:
  databases: null